name: weatherwise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.4.3

  dio: ^5.11.1
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^6.0.1
  shared_preferences: ^2.5.5
  geolocator: ^14.0.2
  fpdart:
  geocoding: ^5.0.0
  flutter_lucide: ^1.47.0
  intl: ^0.20.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter_24pt
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-Black.ttf
          weight: 900
